name: Build Electron for Mac

on:
  workflow_dispatch: # Ini agar kamu bisa menjalankan proses build secara manual via tombol di GitHub

jobs:
  build-mac:
    runs-on: macos-latest # Meminta server dengan OS macOS terbaru

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Sesuaikan dengan versi Node.js yang kamu gunakan

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build:mac 

      - name: Upload Artifact (Hasil Build)
        uses: actions/upload-artifact@v4
        with:
          name: Mac-Application
          path: dist_electron/**/*.dmg
